// brewery-data.jsx — Product catalog + brewery info for Brasserie du Phare

const BREWERY = {
  name: "Brasserie du Phare",
  tagline: "Brassée en bord de mer",
  address: "18 bis Route de Fécamp, 76450 Cany-Barville",
  city: "Cany-Barville",
  region: "Normandie",
  phone: "06 52 96 61 21",
  email: "labrasserieduphare@gmail.com",
  hours: [
    { day: "Lundi",    h: "Fermé" },
    { day: "Mardi",    h: "Fermé" },
    { day: "Mercredi", h: "Fermé" },
    { day: "Jeudi",    h: "17:00 – 22:00" },
    { day: "Vendredi", h: "17:00 – 22:00" },
    { day: "Samedi",   h: "10:00 – 12:00 · 17:00 – 22:00" },
    { day: "Dimanche", h: "Fermé" },
  ],
};

// Beer ranges — every beer has 3 formats (single, 3-pack, 6-pack) except sours which are 33cl singles.
const BEERS = [
  {
    slug: "albatre-pale-ale",
    name: "Albâtre Pale Ale",
    style: "American Pale Ale",
    color: "#3F8F8C",    // teal — matches label
    colorDark: "#19595A",
    colorSoft: "#A8D0CB",
    abv: "4,9°",
    short: "Bière blonde, non filtrée, non pasteurisée.",
    desc: "Inspirée de l'American Pale Ale, blonde et peu amère mais façonnée par les houblons aromatiques français. Idéale à la plage, autour du feu, ou en barbecue.",
    pairings: ["Poissons grillés", "Légumes du soleil", "Fromages doux"],
    ingredients: "Eau de Normandie · Malts d'orge (Pale Ale, Cara Blond BE) · Houblons (Colombus US, Cascade, Bouclier FR) · Levure · Sucre · Contient du gluten",
    serve: "À déguster entre 5 et 7°",
    img: "assets/products/albatre-pale-ale-33cl.jpg",
    formats: [
      { size: "33cl",  price: 3.50, img: "assets/products/albatre-pale-ale-33cl.jpg" },
      { size: "Pack de 3", price: 10.00, img: "assets/products/albatre-pale-ale-3pack.jpg" },
      { size: "Pack de 6", price: 20.00, img: "assets/products/albatre-pale-ale-6pack.jpg" },
    ],
  },
  {
    slug: "red-albatre",
    name: "Red Albâtre",
    style: "Red Ale",
    color: "#D04E37",
    colorDark: "#7E2E1F",
    colorSoft: "#F4C5B6",
    abv: "4,1°",
    short: "Bière rousse, non filtrée, non pasteurisée.",
    desc: "Rafraîchissante et peu amère, la Red Albâtre tient sa couleur rouge cuivrée des malts qui la composent. Notes de caramel et de grains légèrement torréfiés, finale sèche et tonique.",
    pairings: ["Viandes mijotées", "Pommes de terre", "Légumes racines"],
    ingredients: "Eau de Normandie · Malts d'orge (Pilsner, Munich FR, Melano, Ruby BE) · Houblons (Tradition DE, US05) · Sucre · Contient du gluten",
    serve: "À déguster entre 5 et 7°",
    img: "assets/products/red-albatre.jpg",
    formats: [
      { size: "33cl",  price: 3.50, img: "assets/products/red-albatre.jpg" },
      { size: "Pack de 3", price: 10.00, img: "assets/products/red-albatre-3pack.jpg" },
      { size: "Pack de 6", price: 20.00, img: "assets/products/red-albatre-6pack.jpg" },
    ],
  },
  {
    slug: "double-albatre",
    name: "Double Albâtre",
    style: "Double Belge houblonnée",
    color: "#2C5A91",
    colorDark: "#163763",
    colorSoft: "#B0C8E0",
    abv: "7,0°",
    short: "Bière de caractère, non filtrée, non pasteurisée.",
    desc: "Inspirée du style Double Belge, houblonnée comme une américaine et fermentée avec une levure d'abbaye. Identité bien marquée, attaque franche, rondeur charnelle et complexité aromatique : envie d'en reprendre une gorgée.",
    pairings: ["Plateau de fromages", "Gibier", "Tartes au chocolat"],
    ingredients: "Eau de Normandie · Malts d'orge · Malt de froment · Houblons (Colombus, Bouclier) · Levure · Contient du gluten",
    serve: "À déguster entre 7 et 9°",
    img: "assets/products/double-albatre.jpg",
    formats: [
      { size: "33cl",  price: 3.50, img: "assets/products/double-albatre.jpg" },
      { size: "Pack de 3", price: 10.00, img: "assets/products/double-albatre-3pack.jpg" },
      { size: "Pack de 6", price: 20.00, img: "assets/products/double-albatre-6pack.jpg" },
    ],
  },
  {
    slug: "soif",
    name: "Soif",
    style: "Blanche estivale",
    color: "#D17944",
    colorDark: "#8B4724",
    colorSoft: "#F2CCAB",
    abv: "5,0°",
    short: "Bière estivale, désaltérante, non filtrée.",
    desc: "Une bière de Soif ! Le houblon Mandarina y ajoute un agrume et la coriandre vient signer le tout. Pour accompagner un été ensoleillé.",
    pairings: ["Apéritif", "Salades", "Plateau iodé"],
    ingredients: "Eau de Normandie · Malts d'orge · Houblon Mandarina · Levure · Sucre · Épices (coriandre) · Contient du gluten",
    serve: "À déguster entre 5 et 7°",
    img: "assets/products/soif.jpg",
    formats: [
      { size: "33cl",  price: 3.50, img: "assets/products/soif.jpg" },
      { size: "Pack de 3", price: 10.00, img: "assets/products/soif-3pack.jpg" },
      { size: "Pack de 6", price: 20.00, img: "assets/products/soif-6pack.jpg" },
    ],
  },
  {
    slug: "tropical-sour",
    name: "Tropical Sour",
    style: "Sour aux fruits exotiques",
    color: "#E83A8C",
    colorDark: "#A41C5C",
    colorSoft: "#F8C2DA",
    abv: "5,8°",
    short: "Bière acidulée aux fruits exotiques.",
    desc: "Bière de haute fermentation non filtrée et non pasteurisée. Mangue, fruit de la passion, ananas, citron vert — un cocktail acidulé pour les fins d'après-midi qui s'étirent.",
    pairings: ["Tartare de poisson", "Desserts aux fruits", "Apéritif"],
    ingredients: "Eau · Malt d'orge · Malt de froment · Purée de fruits (mangue, fruit de la passion, ananas, citron vert) · Sucre · Houblons · Levures · Contient du gluten",
    serve: "À déguster entre 4 et 6°",
    img: "assets/products/tropical-sour.jpg",
    formats: [
      { size: "33cl",  price: 5.00, img: "assets/products/tropical-sour.jpg" },
    ],
  },
  {
    slug: "white-peach-sour",
    name: "White Peach Sour",
    style: "Sour à la pêche blanche",
    color: "#E89668",
    colorDark: "#9B5A37",
    colorSoft: "#F7D8C2",
    abv: "4,5°",
    short: "Bière acidulée à la pêche blanche, citron vert et verveine.",
    desc: "Bière de haute fermentation non filtrée et non pasteurisée. La pêche blanche s'allie à la verveine pour une finale tout en douceur acidulée.",
    pairings: ["Salades estivales", "Crustacés", "Pâtisseries"],
    ingredients: "Eau · Malt d'orge · Malt de froment · Purée de fruits (pêche blanche, citron vert) · Houblons · Sucre · Levures · Verveine · Contient du gluten",
    serve: "À déguster entre 4 et 6°",
    img: "assets/products/white-peach-sour.jpg",
    formats: [
      { size: "33cl",  price: 5.00, img: "assets/products/white-peach-sour.jpg" },
    ],
  },
  {
    slug: "red-fruits-sour",
    name: "Red Fruits Sour",
    style: "Sour aux fruits rouges",
    color: "#C0294A",
    colorDark: "#7C1C30",
    colorSoft: "#EFB8C5",
    abv: "4,5°",
    short: "Bière acidulée aux fruits rouges.",
    desc: "Fraise, framboise, mûre, cassis — un panier de fruits rouges normands transformé en gorgée acidulée et gourmande.",
    pairings: ["Fromages frais", "Desserts aux fruits", "Apéritif"],
    ingredients: "Eau · Malt d'orge · Malt de froment · Purée de fruits (fraise, framboise, mûre, cassis) · Sucre · Houblons · Levures · Verveine · Contient du gluten",
    serve: "À déguster entre 4 et 6°",
    img: "assets/products/red-fruits-sour.jpg",
    formats: [
      { size: "33cl",  price: 5.00, img: "assets/products/red-fruits-sour.jpg" },
    ],
  },
];

// Resellers / where to find
const RESELLERS = [
  { name: "Cave de la Côte d'Albâtre", city: "Veules-les-Roses",  kind: "Cave" },
  { name: "Le Comptoir des Saveurs",    city: "Fécamp",            kind: "Épicerie fine" },
  { name: "Brasserie La Galère",        city: "Étretat",           kind: "Restaurant" },
  { name: "Marché du Bourg",            city: "Cany-Barville",     kind: "Marché (samedi)" },
  { name: "Le Phare des Saveurs",       city: "Saint-Valery-en-Caux", kind: "Bar à bières" },
  { name: "Hôtel des Falaises",         city: "Yport",             kind: "Hôtel-restaurant" },
  { name: "Cave Normande",              city: "Dieppe",            kind: "Cave" },
  { name: "L'Atelier du Goût",          city: "Rouen",             kind: "Épicerie fine" },
];

// Upcoming events / dégustations
const EVENTS = [
  {
    date: "14 juin 2026",
    dayMonth: { day: "14", month: "JUIN" },
    title: "Visite & dégustation de printemps",
    desc: "Une heure dans nos cuves, suivie d'une dégustation commentée des quatre Albâtre.",
    place: "À la brasserie · 14h",
    price: "15 € / pers.",
  },
  {
    date: "29 juin 2026",
    dayMonth: { day: "29", month: "JUIN" },
    title: "Apéro sur la terrasse — soirée Sour",
    desc: "Première sortie estivale de la Tropical Sour. Foodtruck de la maison Lefranc en accompagnement.",
    place: "Terrasse de la brasserie · 18h",
    price: "Entrée libre",
  },
  {
    date: "13 juillet 2026",
    dayMonth: { day: "13", month: "JUIL" },
    title: "Fête de la bière à Cany-Barville",
    desc: "Stand de la Brasserie sur la place du village avec un fût exclusif brassé pour l'occasion.",
    place: "Place Robert Gabel · toute la journée",
    price: "Gratuit",
  },
  {
    date: "20 septembre 2026",
    dayMonth: { day: "20", month: "SEPT" },
    title: "Atelier brassage amateur",
    desc: "Brasser sa propre bière en petit groupe (8 pers. max). On rentre avec ses bouteilles trois semaines plus tard.",
    place: "À la brasserie · 9h–17h",
    price: "85 € / pers.",
  },
];

Object.assign(window, { BEERS, BREWERY, RESELLERS, EVENTS });
